version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 18
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "CHECK"
leavesCullingAmount = 4
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = true
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
crockpot = true
azurelib = true
edenring = true
mcwfences = true
farmersdelight = true
bountiful = true
mythicmobs = true
forgottengraves = true
spikyspikes = true
croptopia = true
species = true
doapi = true
mythicmounts = true
immersive_portals = true
betternether = true
brewery = true
festive_delight = true
galosphere = true
hamsters = true
enderitemod = true
morefrogs = true
ecologics = true
friendsandfoes = true
natures_spirit = true
runes = true
twigs = true
playdate = true
visualoverhaul = true
sprout = true
dramaticdoors = true
verdantvibes = true
comforts = true
duckling = true
endercage = true
mcwbridges = true
additionaladditions = true
magistuarmory = true
bloomingnature = true
the_bumblezone = true
ftbquests = true
goodending = true
handcrafted = true
herbalbrews = true
tropics = true
snowrealmagic = true
frostiful = true
me = true
betterlily = true
moredelight = true
naturalist = true
exposure = true
furnish = true
spell_engine = true
customportalapi = true
hybrid-aquatic = true
casualness_delight = true
minecells = true
supplementaries = true
paladins = true
deeperdarker = true
beachparty = true
culturaldelights = true
valentines_blessing = true
missingwilds = true
windchimes = true
items_displayed = true
mcopper = true
movingelevators = true
farmersrespite = true
animal_feeding_trough = true
minecraft = true
philipsruins = true
paraglider = true
compressedblocks = true
spawn = true
snifferplus = true
blissful-butterflies = true
underground_jungle = true
travelersbackpack = true
dragonloot = true
waystones = true
creeperoverhaul = true
tradingpost = true
greenscreen = true
xercamusic = true
kafvalentine = true
bushierflowers = true
expandeddelight = true
toms_storage = true
mysticaloaktree = true
desolation = true
candlelight = true
cinderscapes = true
mighty_mail = true
seasonsextras = true
mcwroofs = true
overweight_farming = true
mcwwindows = true
plushables = true
chinesefestivals = true
betterend = true
another_furniture = true
libraryferret = true
automobility = true
stoneworks = true
aquamirae = true
ends_delight = true
snowyspirit = true
mcwpaths = true
nethersdelight = true
magic_vibe_decorations = true
mcde = true
things = true
fastpaintings = true
botanypots = true
mcda = true
amendments = true
evoodooers = true
mcwholidays = true
diagonalfences = true
livingthings = true
bakery = true
advancednetherite = true
soaringstructures2 = true
graveyard = true
netherchested = true
glow_ink_plus = true
corndelight = true
cratedelight = true
pearfection = true
monsters_girls = true
floralench = true
minerally = true
placeable_food = true
chipped = true
winterly = true
convenientdecor = true
biomemakeover = true
geodes = true
bountifulfares = true
luphieclutteredmod = true
plushies = true
treehollows = true
lootr = true
swampier_swamps = true
regions_unexplored = true
expandedstorage = true
betterarcheology = true
epicsamurai = true
nethervinery = true
endermanoverhaul = true
jewelry = true
beautify = true
bosses_of_mass_destruction = true
archers = true
bodacious_berries = true
rocks = true
diagonalwindows = true
oregrowth = true
moyai = true
villagersplus = true
vinery = true
netherdepthsupgrade = true
enchantinginfuser = true
meadow = true
melonslabs = true
grapplemod = true
